---
- name: DotFiles Config
  hosts: localhost
  connection: local


  tasks:

    - name: Determine roles to run
      ansible.builtin.set_fact:
        run_roles: >-
         {{ (ansible_run_tags | difference(['all']) | length > 0) | ternary(ansible_run_tags | difference(['all']), default_roles) | difference(exclude_roles | default([])) | sort }}
      tags: [always]

    # Kommentar hier ist ok – gleiche Ebene wie Tasks

    - name: Run roles
      ansible.builtin.include_role:
        apply:
          tags:
            - "{{ roles_item }}"
        name: "{{ roles_item }}"
      loop_control:
        loop_var: roles_item
      with_items: "{{ run_roles }}"
      tags:
        - always

