---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
  become: true

- name: Ensure dependencies are installed
  ansible.builtin.package:
    name:
      - bc
      - curl
      - expect
      - git
      - ca-certificates
    state: present
  become: true

- name: Create Docker GPG key directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"
  become: true

- name: Download Docker's official GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"
  become: true

# - name: Add Docker repository to Apt sources
#   ansible.builtin.apt_repository:
#     repo: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
#     state: present
#     filename: docker
#   become: true

- name: Docker repo hinzufügen
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/docker.sources
    content: |
      Types: deb
      URIs: https://download.docker.com/linux/ubuntu
      Suites: {{ ansible_distribution_release }}
      Components: stable
      Signed-By: /etc/apt/keyrings/docker.asc
    mode: '0644'
  become: true

- name: Update apt cache after adding Docker repository
  ansible.builtin.apt:
    update_cache: yes
  become: true

- name: Install Docker and Docker Compose
  ansible.builtin.package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  become: true

- name: Ensure Docker service is enabled and started
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes
  become: true

- name: Add ubuntu user to docker group
  ansible.builtin.user:
    name: ubuntu
    groups: docker
    append: yes
  become: true